server:
  port: 8082

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/city_car_status?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

mqtt:
  broker:
    url: tcp://localhost:1883
  client:
    id: smart-city-server
  username: admin
  password: public
  topics:
    pub:
      car-vid: pubCarVID            # 查询主题 - 接收车辆历史数据查询请求
      tip: pubTip                   # 查询主题 - 接收异常信息查询请求
    sub:
      all-msg: subAllMsg           # 响应主题 - 发送所有的历史数据
      history-tip: subHistoryTip   # 响应主题 - 发送异常状态的历史信息
      tip: subTip                  # 接收主题 - 接收异常警报消息
      car-data: subCarData         # 接收主题 - 接收电池数据

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.itdonghuang.entity
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: WARN
    com.itdonghuang: INFO
    com.itdonghuang.mqtt: INFO
    com.itdonghuang.config.MqttConfig: INFO
    org.springframework.integration: WARN
    org.springframework.integration.mqtt: INFO
    org.eclipse.paho.client.mqttv3: WARN
    org.springframework.boot.web.embedded.tomcat: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n" 